### ISSUE TITLE
Any plans to replace mgo with official MongoDB Go driver?

### ISSUE THREAD

**Issue by vlasky** [tulip/oplogtoredis#34]
It appears that [globalsign/mgo](https://github.com/globalsign/mgo) has been unmaintained since October 2018 and people have been switching to [MongoDB's official Go driver](https://github.com/mongodb/mongo-go-driver).

Are there any plans to update oplogtoredis to use MongoDB's driver?

**Comment by jgdef-tulip** [comment]
Thanks in part to your PR @vlasky , the official MongoDB Go driver is in use as of [this commit](https://github.com/tulip/oplogtoredis/commit/8022f42798f075ac789565ad4802525cf8acf830).
