### ISSUE TITLE
Changes between v1.2.0-beta.1 and v2.0.0

### ISSUE THREAD

**Issue by radekmie** [tulip/oplogtoredis#41]
We're using v1.2.0-beta.1 in production for a while now (actually, not that long after it got released), and it really works for us well (even while being hammered with _a lot_ of writes)! I was extremely happy to see that there's some movement in here, and the new release, but there's no information on what changed or whether there are any breaking changes. The bump of the major version suggests some, but maybe that's not the case?

**Comment by jswitzer** [comment]
The big change is the [replacement of mgo with the official mongodb driver](https://github.com/tulip/oplogtoredis/pull/39). This is work that had been done in [vlasky/oplogtoredis](https://github.com/vlasky/oplogtoredis).

This isn't an incompatible change, as far as meteor compatibility is concerned, but would merit some testing for your particular environment (your mongo + redis version, etc) before deployment, just to make sure that the libraries are still compatible with your redis/mongo versions.

The automated regression testing is targeted at mongo 4.4 and redis 6.0.

**Comment by radekmie** [comment]
I can confirm that we're using v2.0.0 in production for a while now and it looks like everything works with MongoDB v4.4.
