### ISSUE TITLE
Support mongo records that use ObjectID instead of string IDs

### ISSUE THREAD

**Issue by benweissmann** [tulip/oplogtoredis#9]
By default, Meteor uses string IDs rather than Mongo's default ObjectIDs. We don't currently support ObjectIDs, but https://github.com/cult-of-coders/redis-oplog/pull/262 adds support in redis-oplog so we should add support here, too.

**Comment by benweissmann** [comment]
Correct behavior is to take the objectid, encoded as hex, and use that as if it were a string in the `_id` field.

**Comment by theodorDiaconu** [comment]
```2018-04-23T15:36:10.282+0300    ERROR   oplogtoredis/main.go:107        op.ID was not a string  {"id": "ObjectIdHex(\"97ae7d05ac945b152789e474\")"}```
